---
# handlers file for deploy_django
- name: restart mysql
  service: name=mysql state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart gunicorn
  service: name=gunicorn state=restarted enabled=yes
