---
# tasks file for deploy_system

- name: Chek and Print LINUX Version
  debug: var=ansible_distribution

- block: #=======blockforRedHat======  
  - name: updating the system
    yum: update_cache=yes
  
  - name: install packages
    yum: pkg={{ item.name }} state=present
    with_items:
      - name: epel-release
      - name: nginx
      - name: git 
      - name: mysql-server
      - name: python3-setuptools
      - name: python3-pip
      - name: python-setuptools
  when: ansible_distribution == "CentOS" 

- block: #======= block for Debian====== 

  - name: Specify MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
    become: true

  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
    become: true

  - name: install packages
    apt: pkg={{ item.name }} state=present
    with_items:
      - name: nginx
      - name: git 
      - name: mysql-server
      - name: python3-setuptools
      - name: python3-pip
      - name: python-setuptools
      - name: python-pymysql
  when: ansible_distribution == "Ubuntu" 

- name: Install required pip packages
  pip:
    name:
      - virtualenv
    executable: pip3


- name: Create MySQL user
  mysql_user: >
    name={{ mysql_user }}
    host=%
    password={{ mysql_user_password }}
    priv={{ mysql_database }}.*:ALL
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
    state=present
  notify:
    - restart mysql

# create database
- name: Create MySQL database
  mysql_db: >
    name={{ mysql_database }}
    collation=utf8_general_ci
    encoding=utf8
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
    state=present
  notify:
    - restart mysql
    
- name: Upload default index.html for host
  copy: src=index.html dest=/var/www/html/index.nginx-debian.html mode=0644
  notify:
    - restart nginx
    
- name: make sure nginx server is running
  service: name=nginx state=started enabled=yes

