version: '3.1'

services:
  db:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db